name: dotSecurity
start: 2017-04-21-13:00:00
end: 2017-04-21-18:00:00
added: 2017-04-17-23:44:00
place: Théâtre des Variétés
address: 7, Boulevard Montmartre
link: 75002 Paris
cfp:
tags: #security #dotSecurity2017
